### ISSUE TITLE
Please configure .DS_Store ignore

### ISSUE THREAD

**Issue by AlexeyBuzdin** [gdgriga/devfestbaltics#37]
https://github.com/gdgriga/devfestbaltics/blob/master/static/images/speakers/.DS_Store

@imeugenia please configure the .gitignore on your Mac
```
# specify a global exclusion list
git config --global core.excludesfile ~/.gitignore
# adding .DS_Store to that list
echo .DS_Store >> ~/.gitignore
```

**Comment by skibish** [comment]
@imeugenia done?

**Comment by imeugenia** [comment]
ups, it's done. Sorry for late reply
